#!/bin/sh

#
# Automatically adds branch name and branch description to every commit message.
#

COMMIT_EDITMSG="$1"

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
AUTHOR_NAME=$GIT_AUTHOR_NAME
AUTHOR_EMAIL=$GIT_AUTHOR_EMAIL

#
# Merge skip the branch placement behavior in commit message.
#

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
    if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "master" ]; then
        COMMIT_EDITMSG=$(sed "s/{{ BRANCH_NAME }}/[${BRANCH_NAME}]:/; s/{{ AUTHOR_NAME }}/${AUTHOR_NAME}/; s/{{ AUTHOR_EMAIL }}/${AUTHOR_EMAIL}/" "$COMMIT_EDITMSG")
    else
        COMMIT_EDITMSG=$(sed "s/{{ BRANCH_NAME }}//; s/{{ AUTHOR_NAME }}/${AUTHOR_NAME}/; s/{{ AUTHOR_EMAIL }}/${AUTHOR_EMAIL}/" "$COMMIT_EDITMSG")
    fi

    echo "${COMMIT_EDITMSG}" > "$1"
fi
